### PR TITLE
update button custom text fix, added modal window custom title text

### PR DESCRIPTION
**Pull request by 10peter10**
Hi, I have to thank you guys for this awesome package.
I just made a few changes. 
1. I added custom text to update button (it was prepared but not used)
2. I added custom text for modal window title (on same way like other custom texts in UpdateCupertinoAlert)

### CODE REVIEW

**Review by amorenew — CHANGES_REQUESTED** [review]
@10peter10 I have reviewed it and it works as expected
I just suggest removing the word custom from _iOSCustomTitle
and it could be _iOSAlertTitle or similar.

It is a very great effort and I hope you get a benefit of using our library
Thanks a lot :)

**Comment by 10peter10** [comment]
Hi, 
I changed the _iOSCustomTitle to _iOSAlertTitle as you suggested,
thank you :) 
It's commit -> 'renamed customTitle to alertTitle'.

**Comment by amorenew** [comment]
@10peter10 you need to open it so I can merge
thank you for your changes

**Comment by 10peter10** [comment]
Sorry, it's open again :)

**Pull request merged**
